=== culturecreates/datascene-serialisation/schema/offer.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://datascene.ca/modele/offer.schema.json",
  "title": "Offre (Offer)",
  "description": "Permet de décrire les propriétés d’une offre associée à une représentation ou une série, par exemple le prix et la disponibilité.",
  "required": [
    "type",
    "inPlace",
    "isSoldout",
    "offerStatus",
    "isAccessibleForFree",
    "isAccessibleFromAnotherOffer",
    "ticketLinkNotAvailable"
  ],
  "type": "object",
  "properties": {
    "type": {
      "const": "Offer"
    },
    "inPlace": {
      "description": "Lieu associé à l'offre (physique ou virtuel).",
      "$ref": "./place.schema.json"
    },
    "inRoom": {
      "description": "Salle associée à l'offre. La salle fait partie du lieu indiqué à la propriété Lieu.",
      "$ref": "./room.schema.json"
    },
    "roomConfiguration": {
      "description": "Configuration de la salle dans le contexte de cette offre.",
      "$ref": "./utilities/room_specification.schema.json"
    },
    "isSoldout": {
      "description": "Permet d'indiquer si cette offre est complète (toutes les places disponibles sont comblées). Peut-être complété par la propriété Complet depuis pour préciser à quelle date l'offre est devenue complète.",
      "type": "boolean"
    },
    "soldoutSince": {
      "description": "Date depuis laquelle l'offre est complète. La propriété Complet doit avoir la valeur vrai pour que Complet depuis puisse être utilisée. Voir https://json-schema.org/understanding-json-schema/reference/type#dates-and-times",
      "type": "string",
      "format": "date-time"
    },
    "offerStatus": {
      "description": "Statut de l'offre. La valeur doit être choisie parmi les valeurs du vocabulaire contrôlé Statut de l'offre.",
      "$ref": "./vocabularies/event_status.schema.json"
    },
    "price": {
      "description": "Prix de départ en dollars canadiens.",
      "$ref": "./datatypes/currency.schema.json"
    },
    "isAccessibleForFree": {
      "description": "Indique que la présente offre est gratuite.",
      "type": "boolean"
    },
    "isAccessibleFromAnotherOffer": {
      "description": "Indique que la présente offre est accessible seulement lorsque le consommateur a souscrit à une autre offre.",
      "type": "boolean"
    },
    "preSaleStart": {
      "description": "Date et heure du début de la prévente. Si la propriété n'est pas documentée, la date de début de disponibilité générale doit être utilisée. Voir https://json-schema.org/understanding-json-schema/reference/type#dates-and-times",
      "type": "string",
      "format": "date-time"
    },
    "generalSaleStart": {
      "description": "Date et heure du début de la disponibilité générale. Si la propriété n'est pas documentée, il faut considérer que l'offre est disponible en tout temps, jusqu'à la date de début et l'heure de la représentation. Voir https://json-schema.org/understanding-json-schema/reference/type#dates-and-times",
      "type": "string",
      "format": "date-time"
    },
    "ticketLinkNotAvailable": {
      "description": "Indication à l'effet qu'il n'existe pas de lien permettant d'obtenir, par le web, un accès à la représentation.",
      "type": "boolean"
    },
    "ticketLink": {
      "description": "URL d'une page permettant de souscire à l'offre, par exemple un lien vers la page de la plateforme de billetterie.",
      "type": "string",
      "format": "uri"
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "isAccessibleForFree": { "const": false },
          "isAccessibleFromAnotherOffer": { "const": false },
          "ticketLinkNotAvailable": { "const": false }
        },
        "required": ["isAccessibleForFree", "isAccessibleFromAnotherOffer", "ticketLinkNotAvailable"]
      },
      "then": {
        "required": ["ticketLink"]
      }
    }
  ]
}

=== culturecreates/datascene-serialisation/data/offre/offre_avec_lien_acquistion.json
{
  "type": "Offer",
  "inPlace": {
    "identifier": [
       "http://123"
    ],
    "type": "Place",
    "virtualPlace": true,
    "name": [{"lang": "fr","value": "Theatre Verdun"}]
  },
  "isSoldout": false,
  "offerStatus": "EventScheduled",
  "isAccessibleForFree": false,
  "isAccessibleFromAnotherOffer": false,
  "ticketLinkNotAvailable": false,
  "ticketLink": "http://example.com/ticket"
}
